name: Send Data to NetDirector SFTP Web API
on:
  workflow_dispatch:
    inputs:
          nd_sftp_username:
            type: string
            description: Username to be created
            required: true
          nd_sftp_bucketname:
            type: string
            description: Bucket Name
            required: true
          nd_sftp_targetpath:
            type: string
            description: Target path if not root
            required: true
            default: /
          nd_sftp_bucketpath:
            type: string
            description: Bucket path required
            required: true
          nd_sftp_password:
            type: string
            description: Password
            required: true
jobs:
  send-data:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to Web API
        env:
          USER_NAME: ${{ inputs.nd_sftp_username }}
          USER_PASS: ${{ inputs.nd_sftp_password }}
          TARGET_PATH: ${{ inputs.nd_sftp_targetpath }}
          BUCKET_NAME: ${{ inputs.nd_sftp_bucketname }}
          BUCKET_PATH: ${{ inputs.nd_sftp_bucketpath }}
        run: |
          curl -X POST https://k6bw01xogf.execute-api.eu-west-1.amazonaws.com \
            -H "Content-Type: application/json" \
            -d '{
              "UserName": "${USER_NAME}",
              "Password": "${USER_PASS}",
              "Target": [{
                  "Entry": "${TARGET_PATH}",
              "Target": "/${BUCKET_NAME}${BUCKET_PATH}"
              }],
              "RoleName": "Production-Transfer-ServiceRole"
                  }'