name: Send Data to NetDirector SFTP Web API
on:
  workflow_dispatch:
    inputs:
          nd_sftp_username:
            type: string
            description: Username to be created
            required: true
          nd_sftp_bucketname:
            type: string
            description: Bucket Name
            required: true
          nd_sftp_targetpath:
            type: string
            description: Target path if not root
            required: true
            default: /
          nd_sftp_bucketpath:
            type: string
            description: Bucket path required
            required: true
          nd_sftp_password:
            type: string
            description: Password
            required: true
jobs:
  send-data:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to Web API
        uses: fjogeleit/http-request-action@v1
        with: 'https://k6bw01xogf.execute-api.eu-west-1.amazonaws.com'
        method: POST
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{
              "UserName": "${{ inputs.nd_sftp_username }}",
              "Password": "${{ inputs.nd_sftp_password }}",
              "Target": [{
                "Entry": "${{ inputs.nd_sftp_targetpath }}",
              "Target": "/${{ inputs.nd_sftp_bucketname }}/${{ inputs.nd_sftp_bucketpath }}"
              }],
              "RoleName": "Production-Transfer-ServiceRole"
              }'